title: my-first-course
description: Esse curso é para iniciar os testes.
template:
  repo: my-first-course-template
  name: my-first-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: Criar um arqivos novo
    actions:
      - type: createIssue
        title: nova issue
        body: a-response-file.md
    description: Criar um arqivos novo
    link: vamos
    event: create
